/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mqikgxqkcqvheigamvjt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xaWtneHFrY3F2aGVpZ2Ftdmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NzM5ODMsImV4cCI6MjA4ODU0OTk4M30.n-oUc8ylCMctne0pBjvGUKd45g1kZQHMvlAk-zS3uVg"